"""create verified_sessions

Revision ID: a8e45d6749cc
Revises: 358967359287
Create Date: 2026-10-08 12:17:35.548221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e45d6749cc'
down_revision: Union[str, None] = '358967359287'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verified_sessions',
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('verified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verified_sessions')
    # ### end Alembic commands ###
